Added detection of zenolib in extern dir as a fallback when it's not detected at the system scope.

diff --git a/components/zenocomponent/configure b/components/zenocomponent/configure
--- a/components/zenocomponent/configure
+++ b/components/zenocomponent/configure
@@ -3073,6 +3073,7 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
+libzeno_found="no"
 
 { echo "$as_me:$LINENO: checking for main in -lzeno" >&5
 echo $ECHO_N "checking for main in -lzeno... $ECHO_C" >&6; }
@@ -3130,13 +3131,85 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_zeno_main" >&5
 echo "${ECHO_T}$ac_cv_lib_zeno_main" >&6; }
 if test $ac_cv_lib_zeno_main = yes; then
-  LIBS="-Wl,-Bstatic -lzeno -lcxxtools -Wl,-Bdynamic $LIBS"
-else
-  { { echo "$as_me:$LINENO: error: libzeno is missing, please install it" >&5
-echo "$as_me: error: libzeno is missing, please install it" >&2;}
-   { (exit 1); exit 1; }; }
+
+	LIBS="-Wl,-Bstatic -lzeno -lcxxtools -Wl,-Bdynamic $LIBS"
+	libzeno_found="yes"
+
 fi
 
+
+if test ! "x$libzeno_found" = "xyes" ; then
+	PWD=`pwd`
+
+	ZENO_CXXFLAGS="-I$PWD/../../../extern/zeno/tntzenoreader/include/"
+	ZENO_LDFLAGS="-L$PWD/../../../extern/zeno/tntzenoreader/src/zenolib/.libs/"
+
+	{ echo "$as_me:$LINENO: checking for main in -lzeno" >&5
+echo $ECHO_N "checking for main in -lzeno... $ECHO_C" >&6; }
+if test "${ac_cv_lib_zeno_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lzeno  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_zeno_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_zeno_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_zeno_main" >&5
+echo "${ECHO_T}$ac_cv_lib_zeno_main" >&6; }
+if test $ac_cv_lib_zeno_main = yes; then
+
+		LIBS="-Wl,-Bstatic -lzeno -lcxxtools -Wl,-Bdynamic $LIBS"
+		libzeno_found="yes"
+
+		CXXFLAGS="$ZENO_CXXFLAGS $CXXFLAGS"
+		LDFLAGS="$ZENO_LDFLAGS $LDFLAGS"
+
+fi
+
+fi
 
 ac_config_files="$ac_config_files Makefile.real"
 
